CREATE TABLE IF NOT EXISTS category (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR(255) NOT NULL UNIQUE CHECK (title <> ''),
    data JSONB,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
